services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: clinicFlowServer
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
    env_file:
      - .env.docker
    volumes:
      - ./server:/server
      - /server/node_modules
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: clinicFlowClient
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://localhost:5000
      - REVALIDATE_SECRET=clinicflow-demo-revalidate
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/client
      - /client/node_modules
    
  mongo:
    image: mongo:7
    container_name: clinicFlow_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - clinicFlow_mongo_data:/data/db
      
  redis:
    image: redis:7-alpine
    container_name: clinicFlow_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - clinicFlow_redis_data:/data
      
  redisinsight:
    image: redis/redisinsight:latest
    container_name: clinicFlow_redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - clinicFlow_redisinsight_data:/data
      
volumes:
  clinicFlow_mongo_data:
  clinicFlow_redis_data:
  clinicFlow_redisinsight_data:
